#domain: louie-cai.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
#url: https://louie-cai.github.io  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /dsc90-wi22-hw06/      # place folder name if the site is served in a subfolder
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
theme: jekyll-theme-hacker